version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/matthias/Server/portainer/data:/data
    labels:
      # Enable Traefik overlay
      - "traefik.enable=true"
      # Router: HTTP redirect
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.benaets.com`)"
      # Router: HHTPS for TLS
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.benaets.com`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      # Middleware
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      # Service
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # Network
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
