version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    volumes:
      - minecraftdata:/data
      - /home/matthias/Server/minecraft/plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      #TYPE: "BUKKIT"                 # Specific modded server
      OPS: "Raaawr"                   # Admin
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true                    # $ docker volume create minecraftdata

# Change server settings:
#   - Full documentation can be found on the github: https://github.com/itzg/docker-minecraft-server/blob/master/README.md
#   - $ docker exec -i minecraft rcon-cli  (or just use portainer to get into contrainer cli)
#   - $ whitelist add/remove <name>
#   - $ difficulty easy/hard
#   - ...
#
# Backups:
#   - Use backup.sh in ./scripts
#   - Add to cronjob: $ crontab -e
#   - 0 0,12 * * * bash /./home/matthias/Server/minecraft/scripts/backup.sh -v minecraftdata -c minecraft -o </path/to/saved/backups> -r false -d 3
#     - This will backup every 12h - run script - backup from volume - from container - in this location - don't delete until 3 days old
# Recover:
#   - $ docker run --rm --volumes-from minecraft -v </path/to/saved/backups>:/backup bash -c "cd /data && tar xvf /backup/<name of backup> --strip 1"
#     - This will remove the volume from container - create a temporary volume with the tar - go into the data folder and uncompress /backup/<name> - and strip all dirs infront of tar
